# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Theme Settings
locale                  : "en-US"
title                   : "Fun in Computing"
subtitle                : "funincomputing.com" #"A science & programming blog" #"A blog by Hossein Ghorbanfekr"
title_separator         : "-"
name                    : "Hossein Ghorbanfekr"
description             : "Fun in Computing: A blog by Hossein Ghorbanfekr"
github_username         : "hghcomphys"
url                     : "http://www.funincomputing.com"
baseurl                 : # the subpath of your site, e.g. "/blog"
repository              : "hghcomphys/hghcomphys" 
minimal_mistakes_skin   : #air
search                  : true
words_per_minute        : 100
masthead_title          : # overrides the website title displayed in the masthead, use " " for no title
teaser                  : /assets/images/cover.jpg
logo                    : /assets/images/logo.png
og_image                : /assets/images/logo.png
# Build settings
markdown                : kramdown
remote_theme            : mmistakes/minimal-mistakes
lsi                     : false
excerpt_separator       : "\n\n"
incremental             : false
# Outputting
permalink               : /:title/ #/:categories/:title/ 
paginate                : 10 # amount of posts to show 
paginate_path           : /page:num/
timezone                : Europe/Brussels
github                  : [metadata]
  
# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

analytics:
  provider: "google"
  google:
    tracking_id: "G-LM1QGB4HYS"
    anonymize_ip: false # default

comments:
  provider: "disqus" # false (default)
  disqus:
    shortname: "funincomputing" #https://funincomputing.disqus.com

author:
  name   : "Hossein Ghorbanfekr"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Research data scientist at VITO"
  location: "Antwerp, Belgium"
  links:
    - label: "LinkdedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/hossein-ghorbanfekr/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hghcomphys"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://hghcomphys.github.io"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:hghcomphys@gmail.com"

footer:
  links:
    - label: "LinkdedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/hossein-ghorbanfekr/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hghcomphys"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://hghcomphys.github.io"
    
defaults:
  #_posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true
      show_date: true
  #_pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
